### ISSUE TITLE
Remove bluebird dependency

### ISSUE THREAD

**Issue by lamuertepeluda** [gatewayapps/node-tnef#14]
Hi there,

I've noticed you are still [using bluebird for wrapping a Promise](https://github.com/gatewayapps/node-tnef/blob/39b4b9a1c156ffabe88fe2aa035cdd9a6b2ea987/src/commands/parse.js#L158). 
But native Promise support for node.js has landed since the long-time deprecated v6, if I am not wrong. Furthermore what what concerns this file, the API is just the same.

What about removing Bluebird dependency? I can make a PR if there are no other reason for keeping it.

**Comment by johnmurphy01** [comment]
@lamuertepeluda No I think it's safe to remove bluebird at this point. I'll look at your PR

**Comment by johnmurphy01** [comment]
Closed via #15

**Comment by lamuertepeluda** [comment]
@johnmurphy01 thanks for merging. Are you going to publish a new version on npm?
