### ISSUE TITLE
Publish a new NPM Version

### ISSUE THREAD

**Issue by lamuertepeluda** [gatewayapps/node-tnef#16]
Hi @johnmurphy01 ,

I saw the latest version on npm is `1.3.0`, while the current package.json version is `1.3.3.`.

Could you please publish an updated version on npm?

**Comment by johnmurphy01** [comment]
Thanks for the info! I will try to get that updated today

**Comment by lamuertepeluda** [comment]
Maybe there is even a mismatch between:

* current release here on github `1.3.0` (2+ years old)
* current package version in npm `1.3.3` (6 months old)
* current package.json version that should be updated, e.g. `1.3.4` or `1.4.0`

I suggest you to fix the release in the package.json, publish a new release tag here and then publish on npm as well

**Comment by johnmurphy01** [comment]
I bumped the version to `1.4.0`, created a new Github release and published to npm. Closing
