### ISSUE TITLE
Parsing MAPI (HTML) content does not work

### ISSUE THREAD

**Issue by andyschr** [gatewayapps/node-tnef#3]
HI there,

thanks for your great work!

I just found out, that the module is not able to parse HTML mime part out of the TNEF file. Unfortunately its not possible to attach a .dat file here (but I can send you via email).

I tried also with the linux command line [tool](https://www.systutorials.com/docs/linux/man/1-tnef/) and also a browser based [(tool)](https://www.winmaildat.com/) - both were able to extract the body.html part of the message.

In the file parse.js from line 239 there is code to decode the MAPI parts - but its always empty.

Do you have a hint for me?

Thanks in advance

**Comment by johnmurphy01** [comment]
When I ported the Go project, I strictly had need of gathering the attachments from the tnef files. Unfortunately, I never tested the module with the express purpose of getting the MAPI content from the file. However, I'll be happy to take a look if you want to send me the file. If you want to use dropbox or another file cloud hosting service and put the link here,  that would be preferable.

**Comment by andyschr** [comment]
Thank you very much for your fast reaction. 
Here you can download the file: 
https://drive.google.com/file/d/1Uuj5riJlf7r20VT4ULH9q5zqDT-npZRF/view?usp=sharing

If I can help you in any way with this - please let me know!

**Comment by andyschr** [comment]
I found a difference between the GO project and this one in function decodeMapi line 19:

`var isMultiValue = (attrType & mvFlag) !== 0
        attrType &= mvFlag`

In the GO project it is 
`
isMultiValue := (attrType & mvFlag) != 0
		attrType &= ^mvFlag 
`

So I think it has to be:
`
var isMultiValue = (attrType & mvFlag) !== 0
        attrType &= ~mvFlag
`

But even with this change it does not work. Maybe there is something else somewhere.

**Comment by johnmurphy01** [comment]
Thanks for that! That isn't the reason for the MAPI parser to not work but
good catch anyway. I'm continuing to investigate and I'll let you know when
I've come up with a solution. If you find anything else, just let me know

**Comment by johnmurphy01** [comment]
I have not yet. I had considered it however. Unfortunately, my time
available to devote to this is limited.

Your proposed fix did appear to do some good. Looking through the output
from parsing the data, it appears as though it is finding data which might
be considered MAPI content. But the marker(or name) of the attribute never
matches the value that I'm looking for (`MAPIBody` and `MAPIBodyHtml`).

If you have time, please by all means run through the GO project and see if
it works any better. If so, then we at least can eliminate the possibility
that the file has something wrong with it.

**Comment by andyschr** [comment]
I just ran the GO library and the MAPI Parts were extracted successfully!

How could I help you further?

**Comment by johnmurphy01** [comment]
That's good to know. So it means that the file is good and there's
something in my port of the code from GO that is incorrect. Feel free to
keep looking, I'll do the same as I have time.

BTW, just so I know what to expect, can you enumerate the files you expect
to see from the TNEF parsing? I'm already getting a .docx file, a JPG and a
PNG.

**Comment by andyschr** [comment]
Hi John,

I just found and fixed the issue.
Will make pull request tomorrow morning!

Best regards

**Comment by johnmurphy01** [comment]
Awesome!

**Comment by johnmurphy01** [comment]
This issue should be fixed in version `1.2.1`. MAPI content can now be parsed. Thanks @andyschr!
