### ISSUE TITLE
parseBuffer, always return TRUE for first argument of callback

### ISSUE THREAD

**Issue by r3bo0t** [gatewayapps/node-tnef#8]
https://github.com/gatewayapps/node-tnef/blob/master/src/commands/parse.js#L124

This implies, we can't use util.promisify for this.

**Comment by johnmurphy01** [comment]
@r3bo0t I just pushed an update(version `1.3.1`). Please let me know if you are now able to promisify  this function.

**Comment by r3bo0t** [comment]
@johnmurphy01 Don't you think, its should be other way around, true for error case and false for normal case?
https://github.com/gatewayapps/node-tnef/blob/master/src/commands/parse.js#L129

**Comment by johnmurphy01** [comment]
@r3bo0t I think you're right. I've updated and published a new version(`1.3.2`)
